"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Edit, Download } from "lucide-react";

export function ItineraryPlanner() {
  const [activeTab, setActiveTab] = useState("generator");
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [selectedsource, setSelectedsource] = useState("");
  const [selecteddestination, setSelecteddestination] = useState("");
  const [selectedstart, setSelectedstart] = useState("");
  const [selectedend, setSelectedend] = useState("");
  const [selectedInterest, setSelectedInterest] = useState("");
  const [selectedBudget, setSelectedBudget] = useState("");
  const [numberOfTravelers, setNumberOfTravelers] = useState("");
  const [selectedAccommodation, setSelectedAccommodation] = useState("");
  const [selectedMeal, setSelectedMeal] = useState("");
  const [specialRequirements, setSpecialRequirements] = useState("");
  const [itinerary, setItinerary] = useState<string>("");

  const handleGenerate = async () => {
    if (!selectedsource || !selecteddestination || !selectedstart || !selectedend || !selectedInterest || !selectedBudget) {
      alert("Please fill all required fields.");
      return;
    }

    const today = new Date();
    const minStartDate = new Date("2025-03-25");
    const selectedStartDate = new Date(selectedstart);
    
    if (selectedStartDate < minStartDate) {
      alert("Start date cannot be earlier than 25.03.2025.");
      return;
    }
    
    const selectedEndDate = new Date(selectedend);
    if (selectedEndDate < selectedStartDate) {
      alert("End date cannot be earlier than start date.");
      return;
    }
  
    setGenerating(true);
    setGenerated(false);
    setItinerary("");
  
    try {
      const response = await fetch("http://localhost:5000/api/generate-itinerary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          interest: selectedInterest,
          budget: selectedBudget,
          source: selectedsource,
          destination: selecteddestination,
          startDate: selectedstart,
          endDate: selectedend,
          numberOfTravelers: numberOfTravelers || "1",
          accommodation: selectedAccommodation || "None",
          meal: selectedMeal || "No Preference",
          specialRequirements: specialRequirements.trim() || "None"
        }),
      });
  
      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to generate itinerary");
      }
  
      setItinerary(data.itinerary);
      setGenerated(true);
    } catch (error) {
      console.error("API request failed:", error);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadPDF = () => {
    import('jspdf').then(({ jsPDF }) => {
      const doc = new jsPDF();
      const marginLeft = 15;
      const marginTop = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const maxWidth = pageWidth - marginLeft * 2;
      let lineHeight = 7;
      let currentY = marginTop;
      
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      const title = `Trip Itinerary: ${selectedsource} to ${selecteddestination}`;
      doc.text(title, pageWidth / 2, currentY, { align: 'center' });
      currentY += lineHeight * 2;
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      const dates = `Travel Dates: ${new Date(selectedstart).toLocaleDateString()} - ${new Date(selectedend).toLocaleDateString()}`;
      doc.text(dates, pageWidth / 2, currentY, { align: 'center' });
      currentY += lineHeight * 2;
      
      doc.setDrawColor(200, 200, 200);
      doc.line(marginLeft, currentY, pageWidth - marginLeft, currentY);
      currentY += lineHeight * 1.5;
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      lineHeight = 6;
      
      const paragraphs = itinerary.split('\n').filter(p => p.trim());
      
      paragraphs.forEach(paragraph => {
        const lines = doc.splitTextToSize(paragraph, maxWidth);
        
        if (currentY + (lines.length * lineHeight) > doc.internal.pageSize.getHeight() - 20) {
          doc.addPage();
          currentY = marginTop;
        }
        
        doc.text(lines, marginLeft, currentY);
        currentY += lines.length * lineHeight + 5;
      });
      
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Generated by Travel Planner AI", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
      
      doc.save(`Itinerary_${selectedsource}_to_${selecteddestination}.pdf`);
    }).catch(err => {
      console.error('Failed to generate PDF:', err);
    });
  };

  return (
    <div className="space-y-6">
      <Tabs defaultValue="generator" className="w-full" onValueChange={setActiveTab}>
        <TabsList className="grid grid-cols-2 w-full">
          <TabsTrigger value="generator">AI Generator</TabsTrigger>
          <TabsTrigger value="saved">Saved Itineraries</TabsTrigger>
        </TabsList>

        <TabsContent value="generator" className="mt-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Generate Your Perfect Itinerary</CardTitle>
                <CardDescription>Tell us about your trip and preferences</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">Source</Label>
                    <Input
                      name="source"
                      placeholder="e.g. Pune, Hyderabad"
                      value={selectedsource}
                      onChange={(e) => setSelectedsource(e.target.value)}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label className="text-sm font-medium">Destination</Label>
                    <Input
                      name="destination"
                      placeholder="e.g. Pune, Hyderabad"
                      value={selecteddestination}
                      onChange={(e) => setSelecteddestination(e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label className="text-sm font-medium">Travel Dates</Label>
                  <div className="grid grid-cols-2 gap-4">
                    <Input
                      type="date"
                      name="startDate"
                      min="2025-03-25"
                      value={selectedstart}
                      onChange={(e) => setSelectedstart(e.target.value)}
                    />
                    <Input
                      type="date"
                      name="endDate"
                      value={selectedend}
                      onChange={(e) => setSelectedend(e.target.value)}
                    />
                  </div>
                </div>

                <div className="flex flex-wrap -mx-2">
                  <div className="w-1/2 px-2 space-y-2">
                    <label className="text-sm font-medium">Interests</label>
                    <select
                      className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:ring-blue-300"
                      value={selectedInterest || "ALL"}
                      onChange={(e) => setSelectedInterest(e.target.value)}
                    >
                      {["ALL", "Culture", "Food", "Nature", "Shopping", "History", "Art", "Adventure", "Relaxation"].map((interest) => (
                        <option key={interest} value={interest}>
                          {interest}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="w-1/2 px-2 space-y-2">
                    <label className="text-sm font-medium">Budget Amount</label>
                    <input
                      type="number"
                      className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:ring-blue-300"
                      value={selectedBudget}
                      onChange={(e) => setSelectedBudget(e.target.value)}
                      placeholder="Enter your budget"
                      min="0" // Prevents negative values
                    />
                  </div>


                  <div className="w-1/2 px-2 space-y-2">
                    <label className="text-sm font-medium">Meal Preferences</label>
                    <select
                      className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:ring-blue-300"
                      value={selectedMeal || "No Preference"}
                      onChange={(e) => setSelectedMeal(e.target.value)}
                    >
                      {["No Preference", "Vegetarian", "Vegan", "Non-Vegetarian"].map((meal) => (
                        <option key={meal} value={meal}>
                          {meal}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="w-1/2 px-2 space-y-2">
                    <label className="text-sm font-medium">Number of Travelers</label>
                    <input
                      type="number"
                      min="1"
                      className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:ring-blue-300"
                      value={numberOfTravelers}
                      onChange={(e) => setNumberOfTravelers(e.target.value)}
                      placeholder="Enter number of travelers"
                    />
                  </div>

                  <div className="w-1/2 px-2 space-y-2">
                    <label className="text-sm font-medium">Accommodation Preference</label>
                    <select
                      className="w-full px-3 py-2 border rounded-md focus:outline-none focus:ring focus:ring-blue-300"
                      value={selectedAccommodation || "No Preference"}
                      onChange={(e) => setSelectedAccommodation(e.target.value)}
                    >
                      {["No Preference", "Budget Stay", "Mid-Range Hotel", "Luxury Resort", "Hostel", "Airbnb", "Boutique Hotel"].map(
                        (option) => (
                          <option key={option} value={option}>
                            {option}
                          </option>
                        )
                      )}
                    </select>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label className="text-sm font-medium">Special Requirements</Label>
                  <Textarea
                    placeholder="e.g. Traveling with kids, accessibility needs, dietary restrictions..."
                    value={specialRequirements}
                    onChange={(e) => setSpecialRequirements(e.target.value)}
                  />
                </div>
              </CardContent>
              <CardFooter>
                <Button 
                  className="w-full" 
                  onClick={handleGenerate} 
                  disabled={generating || !selectedInterest || !selectedBudget}
                >
                  {generating ? "Generating..." : "Generate"}
                </Button>
              </CardFooter>
            </Card>

            <Card className={generated ? "" : "opacity-60"}>
              <CardHeader>
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle>Your Itinerary</CardTitle>
                    <CardDescription>
                      {generated ? "Generated travel plan" : "Waiting for AI to generate..."}
                    </CardDescription>
                  </div>
                  {generated && (
                    <Badge className="bg-blue-600 text-white">
                      <Sparkles className="mr-1 h-3 w-3" />
                      AI Generated
                    </Badge>
                  )}
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {generated ? (
                  itinerary.split("\n").map((paragraph, index) => (
                    paragraph.trim() && <p key={index} className="text-sm">{paragraph}</p>
                  ))
                ) : (
                  <p className="text-sm text-muted-foreground">Click "Generate" to create your itinerary.</p>
                )}
              </CardContent>

              <CardFooter className="flex justify-between">
                <Button variant="outline" size="sm">
                  <Edit className="mr-1 h-4 w-4" />
                  Edit
                </Button>
                <Button 
                  size="sm"
                  onClick={handleDownloadPDF}
                  disabled={!generated}
                >
                  <Download className="mr-1 h-4 w-4" />
                  Export
                </Button>
              </CardFooter>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}